import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import utilStyles from '@/styles/utilis.module.css'
import {getSortedPostsData} from '../lib/posts';
import Link from 'next/link'

export default function Home({allPostsData}) {
  return (
      <>
      <Head>
    <title>Lee_blog</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
  <main className={`${styles.main} ${utilStyles.bckgrnd}`}>
<div className={utilStyles.headx} >
  <p className= {styles.description} >
        Venture the Adventures of our Business&nbsp;
  </p>
</div>
    <section>
      <h2 className={utilStyles.headingx2}><u>About</u></h2>
          <ul className = {utilStyles.blog}>
            
            {allPostsData.map (({id, date, title}) => (
              <li className={utilStyles.classes} >
                {title}
                <br/>
                {id}
                <br/>
                {date}
              </li>
            ))}
          </ul>
    </section>
  </main>
   </>   
  )
}
export async function getStaticProps () 
{
  const allPostsData = getSortedPostsData();
  return {
    props: {
      allPostsData,
    },
  };
}

