import Head  from 'next/head'
import utilStyles from '../styles/utils.module.css'
import Link from 'next/link'
import Image from 'next/image'

export default function Home() {
  return (
      <main>
  <Head>
    <title>Lee_blog</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>

  <main>
    <div> 
      <h1>LEE BUSINESS BLOG</h1>
    </div>
<div className={utilStyles.venture}>
  <p>
        Venture the Adventures of our Business&nbsp;
  </p>
</div>
    <section>
      <ul className={utilStyles.lee}>
      <h1>About</h1>
              
                <h3><Link href="posts/market">  Marketing  </Link></h3> 
                <h3><Link href="posts/innovation">Innovation</Link></h3>
                <h3><Link href="posts/management">Management</Link></h3>
                <h3><Link href="posts/faqs">FAQs</Link></h3> 
                <h3><Link href="posts/resources">Resources</Link></h3>          
          </ul>
    </section>
  </main>
   </main>   
  )
}
